import numpy as np
matrix1=np.array([[1,2],[3,4]])
matrix2=np.array([[5,6],[7,8]])
sum=np.add(matrix1,matrix2)
trnsp=np.transpose(matrix1)
print("M1=",matrix1)
print("M2=",matrix2)
print("Sum=",sum)
print("transpose ofthe matrix1=",trnsp)
diff=np.subtract(matrix2,matrix1)
print("Difference=",diff)
matrix3=np.array([[144,4],[25,36]])
sqrt=np.sqrt(matrix3)
print("squareroot=",sqrt)
prdct=np.multiply(matrix1,matrix2)
print("product of the matrix =",prdct)
dprt=np.dot(matrix1,matrix2)
print("dot product=",dprt)
